# -*- coding: utf-8 -*-
"""Coding SEIR Kusta .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12w3mFOtYJKI__yq5zROQxoAJQciozKEo
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

def kusta(y, t, beta, sigma, gamma, mu, nu):
    S, E, I, R = y
    dSdt = nu - beta * S * I - mu * S
    dEdt = beta * S * I - sigma * E - mu * E
    dIdt = sigma * E - gamma * I - mu * I
    dRdt = gamma * I - mu * R
    return [dSdt, dEdt, dIdt, dRdt]


N = 1000000
beta = 0.02
sigma = 0.001
gamma = 0.002
mu = 0.000039
nu = 0.03
I0 = 1
E0 = 0
R0 = 0
S0 = N-1
t = np.linspace(0, 20000, 20000)

solusi = odeint(kusta, [S0, E0, I0, R0], t, args=(beta, sigma, gamma, mu, nu))
S, E, I, R = solusi.T

plt.figure(figsize=(10,6))
plt.plot(t, S, label='Susceptible', color='blue')
plt.plot(t, E, label='Exposed', color='orange')
plt.plot(t, I, label='Infected', color='red')
plt.plot(t, R, label='Recovered', color='green')
plt.xlabel('Hari')
plt.ylabel('Jumlah Individu')
plt.title('Model SEIR untuk Penyakit Kusta')
plt.legend()
plt.grid()
plt.show()