# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wA__Z0iGhvbV4LFbsj3syhq5CAyBVYFl
"""

import numpy as np
import matplotlib.pyplot as plt

# Fungsi untuk menyelesaikan persamaan diferensial secara analitik
def penurunan_suhu(Ta, t, T0, k):
    """
    Menyelesaikan P(t) = Ta + e^(r * t)*To

    Parameter:
    Ta : Suhu Ruangan
    t : array-like, titik waktu
    T0 : float, Suhu Awal
    k : float, laju pertumbuhan

    Mengembalikan:
    P : array-like, konstanta laju perbandinganan suhu
    """

    return  Ta + np.exp(-1*k * t) * T0

# Parameter contoh
T0 = 90  # Suhu awal
Ta = 30   # Suhu Ruangan
t = np.linspace(0, 120, 200)  # Titik waktu dari 0 hingga 120
k = 0.03

# Menyelesaikan persamaan
Pa = pertumbuhan_populasi(Ta, t, T0, k)
# Plot hasilnya
plt.figure(figsize=(8, 6))
plt.plot(t, Pa, label=f"P(t) = {T0} * exp({-k} * t)", color="blue")
plt.title("Pendinginan Suhu Kopi")
plt.xlabel("Waktu (t)")
plt.ylabel("Suhu")
plt.legend()
plt.grid()
plt.show()