# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnSxArtXhA6GH07iyuFAg0LJ_bfzZQyU
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameter model logistik
K = 5  # Kapasitas maksimum (kg)
P0 = 0.2  # Berat awal (kg)
r = 0.3  # Laju pertumbuhan intrinsik (per minggu)
t = np.linspace(0, 20, 100)  # Waktu (minggu)

# Solusi eksplisit model logistik
def pertumbhn(t, K, P0, r):
    return K / (1 + ((K - P0) / P0) * np.exp(-r * t))

# Hitung berat kubis pada setiap waktu t
P = pertumbhn(t, K, P0, r)

# Plot hasil
plt.figure(figsize=(8, 6))
plt.plot(t, P, label='Pertumbuhan Logistik', color='green')
plt.axhline(K, color='red', linestyle='--', label='Kapasitas Maksimum (K)')
plt.title('Model Pertumbuhan Logistik Kubis')
plt.xlabel('Waktu (minggu)')
plt.ylabel('Berat Kubis (kg)')
plt.legend()
plt.grid(True)
plt.show()