# -*- coding: utf-8 -*-
"""Tugas 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16BKs15junX9DJRoSsZ_HFjSk32Mwscps
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

def sir_model(y, t, beta, alpha, gamma, sigma, N):
    S, I, R = y
    dSdt = alpha * N - beta * S * I / N - sigma * S
    dIdt = beta * S * I / N - gamma * I - sigma * I
    dRdt = gamma * I - sigma * R
    return [dSdt, dIdt, dRdt]


N = 1000
alpha = 0.01
beta = 0.3
gamma = 0.1
sigma = 0.01

S0 = N - 1
I0 = 1
R0 = 0
y0 = [S0, I0, R0]
t = np.linspace(0, 160, 1000)

solution = odeint(sir_model, y0, t, args=(beta, alpha, gamma, sigma, N))
S, I, R = solution.T

plt.figure(figsize=(10, 6))
plt.plot(t, S, label="Susceptible", color="blue")
plt.plot(t, I, label="Infected", color="red")
plt.plot(t, R, label="Recovered", color="green")
plt.xlabel("Time (days)")
plt.ylabel("Population")
plt.legend()
plt.grid()
plt.title("SIR Model dengan laju Kematian dan Kelahiran")
plt.show()