# -*- coding: utf-8 -*-
"""HIV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ymsh6Zkdv4h8VtCCT9gtlRSSQctf2eVF
"""

import numpy as np
import matplotlib.pyplot as plt

#parameter model
N = 1000
beta = 0.002
gamma = 0.1
mu = 0.01
delta = 0.2

#kondisi awal
H0 = 900
I0 = 80
V0 = 20

#waktu mulai
T = 100
dt = 1
#vektor waktu
time = np.arange(0, T + dt, dt)
#array untuk menyimpan hasil simul;asi
H = np.zeros(len(time))
I = np.zeros(len(time))
V = np.zeros(len(time))
H[0] = H0
I[0] = I0
V[0] = V0
#simul;asi dengan metode euler
for t in range(1, len(time)):
  dH = mu *N- beta *H[t-1]*I[t-1]-mu*H[t-1]
  dI = beta * H[t-1] * I[t-1]-(gamma+mu)*I[t-1]
  dV = gamma*I[t-1]-(delta+mu)*V[t-1]
  # update popiulasi
  H[t] = H[t-1] +dH*dt
  I[t] = I[t-1] + dI * dt
  V[t] = V[t-1] + dV * dt

#plot hasil simulasi

plt.figure(figsize=(10,6))
plt.plot(time, H, label='rentan (H)', color = 'blue')
plt.plot(time, I, label='terinveksi hiv', color = 'orange')
plt.plot(time, V, label='Aids', color = 'red')


plt.title('simulasi penyebaran HiV selama 100 hari')
plt.xlabel('Hari')
plt.ylabel('jumlah pupulasi')
plt.legend()
plt.grid(True)
plt.show()

print('daniel' + 'ranu')