# -*- coding: utf-8 -*-
"""Lotka Voltera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JTMgOYrqQ2aWr-bTAZFSrPQwM4JJ_8GD
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint
#parameter model
alpha = 0.5
beta = 0.02
delta = 0.01
gamma = 0.3

# persamaan diferensial lotka-volterra
def lotka_volterra(y, t, alpha, beta, delta, gamma):
 x, y = y
 dxdt = alpha * x - beta *x * y
 dydt = delta * x * y - gamma * y
 return [dxdt, dydt]

#kondisi awal
y0 = [40, 9]
# rentan waktu
t = np.linspace(0, 200, 10000)
# menyelesaikan persamaaan
solution = odeint(lotka_volterra, y0, t, args=(alpha, beta, delta, gamma))
rusa, serigala = solution.T
#membuat grafik
plt.figure(figsize=(10,5))
plt.plot(t, rusa, label='rusa', color='blue', linewidth=2)
plt.plot(t, serigala, label='serigala', color='red', linewidth=2)
plt.xlabel('waktu')
plt.ylabel('jumlah populasi')
plt.title('simulasi lotkavolterra')
plt.legend()
plt.grid()
plt.